name: Read-only check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Block push
        run: |
          echo "Repo này chỉ ở chế độ Read-only."
          exit 1
